baseURL = https://www.automationexercise.com/
loginURL = https://www.automationexercise.com/login
signupURL = https://www.automationexercise.com/signup
SignupConfirmationPage = https://www.automationexercise.com/account_created
emailAlreadyExists = Email Address already exist!
subscription = SUBSCRIPTION
successfullySubscribed = successfully subscribed
successfullySubmitted = Success! Your details have been submitted successfully.
allProductText = ALL PRODUCTS
availabilityMessage = Availability
conditionMessage = Condition
brandMessage = brands
brandMessageB = Brand
reviewMessage = Write Your Review
reviewThanks = Thank you
TestCasesAssertionMessage = Below is the list of test Cases for you to practice the Automation