baseURL = https://www.automationexercise.com/
loginURL = https://www.automationexercise.com/login
apptitle = Swag Labs
errorMSG = Epic sadface: Username and password do not match any user in this service
lockedoutMSG = Epic sadface: Sorry, this user has been locked out.
usernameRequiredMessage = Epic sadface: Username is required
passwordRequiredMessage = Epic sadface: Password is required