baseURL = https://www.automationexercise.com/
homeURL = https://www.saucedemo.com/inventory.html
apptitle = Swag Labs
errorMSG = Epic sadface: Username and password do not match any user in this service
lockedoutMSG = Epic sadface: Sorry, this user has been locked out.
usernameRequiredMessage = Epic sadface: Username is required
passwordRequiredMessage = Epic sadface: Password is required